[buildPlans.penrose-mono]
family = "Penrose Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.penrose-mono.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
seven = "straight-serifless"
eight = "crossing"
nine = "straight-bar"
zero = "tall-slashed"
capital-b = "standard-serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-serifless"
capital-q = "crossing-baseline"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
b = "toothed-serifless"
d = "toothed-serifless"
f = "flat-hook-serifless"
g = "single-storey-serifless"
k = "symmetric-touching-serifless"
m = "serifless"
n = "straight-serifless"
r = "hookless-serifless"
t = "flat-hook-short-neck"
w = "straight-flat-top-serifless"
y = "straight-serifless"
lower-eth = "straight-bar"
lower-lambda = "straight"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
asterisk = "penta-low"
caret = "low"
ascii-grave = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
at = "fourfold-solid-inner-tall"
dollar = "through"
percent = "dots"
bar = "force-upright"
question = "smooth"
decorative-angle-brackets = "middle"
lig-equal-chain = "with-notch"

  [buildPlans.penrose-mono.ligations]
  inherits = "dlig"

[buildPlans.penrose-mono.weights.Light]
shape = 400
menu = 400
css = 400

[buildPlans.penrose-mono.weights.Regular]
shape = 500
menu = 500
css = 500

[buildPlans.penrose-mono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.penrose-mono.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.penrose-mono.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.penrose-mono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.penrose-mono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.penrose-mono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.penrose-term]
family = "Penrose Term"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = false
export-glyph-names = false

[buildPlans.penrose-term.variants]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-term.weights]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-term.widths]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-term.slopes]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-sans]
family = "Penrose Sans"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
noCvSs = false
export-glyph-names = false

[buildPlans.penrose-sans.variants]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-sans.weights]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-sans.widths]
inherits = "buildPlans.penrose-mono"

[buildPlans.penrose-sans.slopes]
inherits = "buildPlans.penrose-mono"
